[package]
name = "influxproxy"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "*"
axum = "0.4.*"
tokio = { version = "1.17.*", features = ["full"]}
serde = "1.0.*"
serde_json = "1.0.*"
serde_derive = "1.0.*"
tracing = "0.1.*"
tracing-subscriber = "0.3.*"
structopt = "0.*"
reqwest = "0.11.*"